name: weather_space
description: "[WS] Weather Space."

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get_it: ^7.2.0
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  retrofit_generator: ^9.1.2
  json_serializable: ^6.0.1
  analyzer: ^6.7.0

flutter:
  generate: true
